repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: trailing-whitespace

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
        args: [--safe, --quiet]

  - repo: https://github.com/pycqa/isort
    rev: 9.0.0a3
    hooks:
      - id: isort


ci:
  autoupdate_schedule: quarterly
